---
- name: Register instances {{instance_ids}}
  local_action: ec2_elb
  args:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    ec2_elbs: "{{ elb_name }}"
    region: "{{ region }}"
    instance_id: "{{ item.id }}"
    validate_certs: no
    enable_availability_zone: yes
    wait: yes
    state: present
  with_items: "{{ ec2.instances }}"
