- hosts: localhost
  connection: local
 
      
  tasks:
  - name: Launch Instance
    ec2:
      group_id: "{{ ec2_sg_id }}"
      count: "{{ ec2_count }}"
      keypair: "{{ ec2_key_name }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_base_image }}"
      wait: true
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
      monitoring: "{{ ec2_monitoring }}"
      assign_public_ip: "{{ ec2_assign_public_ip }}"
      instance_tags:
         Name: "{{ server }}"
         Approver: "{{ Approver }}"
         Expireday: "{{ expday }}"
    register: ec2

 

  - name: Wait for SSH to come up
    local_action: wait_for
                  host={{ item.private_ip }}
                  port="{{ PORT }}"
                  state=started
    with_items: "{{ ec2.instances }}"

  #- name: Add dynamic host and variable
  #  add_host:
  #     name: "{{ item.private_ip }}"
  #     groups: aws
  #     service: "{{ server }}"
  #     ansible_ssh_user: "{{ USER }}"
  #     ansible_ssh_pass: "{{ PASSWD }}"
  #     ansible_sudo_pass: "{{ PASSWD }}"
  #     ansible_ssh_port: "{{ PORT }}"
  #   #  ansible_ssh_private_key_file: /home/awsdev/pp-environment.pem
  #  with_items: "{{ ec2.instances }}"

#- hosts: aws 
#  become: yes
#  become_user: root

#  tasks:

#    - include: "{{ path }}/roles/ServerStart/tasks/symentic.yml"
#    - include: "{{ path }}/roles/ServerStart/tasks/ossec.yml"


#- hosts: aws
#  gather_facts: True
#  become: yes
#  become_user: root
#  roles:
#    - "{{ path }}/roles/pci/"




    

    

    
 